#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
[package]
name = "zenoh_backend_influxdb"
version = "0.6.0-dev.0"
authors = [
    "kydos <angelo@icorsaro.net>",
    "Julien Enoch <julien@enoch.fr>",
    "Olivier Hécart <olivier.hecart@zettascale.tech>",
    "Luca Cominardi <luca.cominardi@zettascale.tech>",
]
edition = "2018"

[lib]
name = "zbackend_influxdb"
crate-type = ["cdylib"]

[dependencies]
zenoh_backend_traits = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes" }
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes" }
zenoh-buffers = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes" }
zenoh-core = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes" }
zenoh-collections = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes" }
zenoh-cfg-properties = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "api-changes" }
async-std = "=1.12.0"
async-trait = "0.1.42"
lazy_static = "1.4.0"
env_logger = "0.9.0"
humantime = "2.1.0"
log = "0.4"
git-version = "0.3.4"
uuid = { version = "1.1.2", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
base64 = "0.13.0"
influxdb = { version = "0.5.2", default-features = false, features = [
    "derive",
    "use-serde",
    "h1-client-rustls",
] }

[build-dependencies]
rustc_version = "0.4.0"

[package.metadata.deb]
name = "zenoh-backend-influxdb"
maintainer = "zenoh-dev@eclipse.org"
copyright = "2022 ZettaScale Technology"
section = "net"
license-file = ["LICENSE", "0"]
depends = "zenoh-plugin-storage-manager (=0.6.0~dev.0)"
